### ISSUE TITLE
Should be able to output a directory rather than absolute path to output file

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/pmix#7]
## Description
I tried to output to a directory `-o output/` rather than specifying an absolute path to an output file, e.g. `- output/result.xlsx`, and I got an error.

## Example command
`python3 -m pmix.borrow input/target/KER7-Female-Questionnaire-v4-jef.xlsx input/source/translations-KER7-2018.10.02-v4-jef.xlsx -o output/`

### Error received
```
Exception ignored in: <bound method Workbook.__del__ of <xlsxwriter.workbook.Workbook object at 0x10470aef0>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xlsxwriter/workbook.py", line 153, in __del__
    raise Exception("Exception caught in workbook destructor. "
Exception: Exception caught in workbook destructor. Explicit close() may be required for workbook.
```

### Full log
```
Joe:borrow-web test joeflack4$ python3 -m pmix.borrow input/target/KER7-Female-Questionnaire-v4-jef.xlsx input/source/translations-KER7-2018.10.02-v4-jef.xlsx -o output/
Namespace(add=None, carry=False, correct=None, diverse=None, ignore=None, merge=None, merge_all=None, no_diverse=False, outpath='output/', xlsxfile=['input/target/KER7-Female-Questionnaire-v4-jef.xlsx', 'input/source/translations-KER7-2018.10.02-v4-jef.xlsx'])
"Interviewer's name


Please record your name as a witness to the consent process. You previously entered "${name_typed}."" has 2 translations in "Swahili" language: ['Interviewer\'s name\n\n\nPlease record your name as a witness to the consent process. You previously entered "${name_typed}."', 'jina la mhoji\n\nTafadhali andika jina lako kama shahidi wa utaratibu wa kupata kibali. Ulijaza awali "$ {jina_typed}".']
"Do not know" has 2 translations in "Swahili" language: ['Hajui', 'Sijui']
"Other" has 2 translations in "Swahili" language: ['Nyingine', 'Sababu nyengine']
"Questionnaire Result" has 2 translations in "Swahili" language: ['Nakili matokea ya mahojiano', 'Nakili matokeo ya mahojiano']
Exception ignored in: <bound method Workbook.__del__ of <xlsxwriter.workbook.Workbook object at 0x10470aef0>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xlsxwriter/workbook.py", line 153, in __del__
    raise Exception("Exception caught in workbook destructor. "
Exception: Exception caught in workbook destructor. Explicit close() may be required for workbook.
Created translation file: "output/"
Joe:borrow-web test joeflack4$ ls
input   output
Joe:borrow-web test joeflack4$ tree
.
├── input
│   ├── source
│   │   └── translations-KER7-2018.10.02-v4-jef.xlsx
│   └── target
│       └── KER7-Female-Questionnaire-v4-jef.xlsx
└── output

4 directories, 2 files
Joe:borrow-web test joeflack4$
```

### Previous discussion
_See comments._

### Proposed solution
**From:**
```
wb = xlsxwriter.Workbook(path)
```

**To:**
```
filepath = path + 'result.xlsx' if os.path.isdir(path) else path
wb = xlsxwriter.Workbook(filepath)
```

May also want to implement a wrapper class for Workbook if needed for abstraction purposes.

**Comment by joeflack4** [comment]
## Previous discussion
_James_
> The write_out routine here should not know how to deal with directories.

_Joe_
> I disagree. I think this is the correct place to put this. Otherwise, handling for directories has to be implemented in every single tool that utilizes write_out(), creating duplication of efforts. If you still disagree, let's chat about this over voice perhaps.

_James_
> It is the wrong level of abstraction. Take a look at xlsxwriter itself. https://xlsxwriter.readthedocs.io/workbook.html and ask yourself why they don't allow you to give a directory. Another reason why it isn't a good abstraction is the fact that you are using a "magic value" with result.xlsx. Plus, there is currently only one routine that we allow to call this using a directory. That is hardly justification to worry about "every single tool"

_Joe_
> @jkpr It will be easier to enumerate these points:
> i. Correct level of abstraction: I agree that xlsxwriter.Workbook is the wrong level of abstraction. But I believe that our wrapper class in pmix is a good / correct level of abstraction for this. If not, then we'd need another wrapper class around our wrapper class, and I'm just not sure how useful that would be.
> ii. Magic value: I think there's no way around that. Any situation I've seen where a file is written out but no file name has been given will have to choose (and does choose) a default value.
> iii. DRYness and UX: Borrow isn't the only tool that uses pmix.Workbook. Numbering and workbook_cli() also use it and also accept --outpath via the CLI. XLSDiff uses it, though it automatically adds a -diff to the file name for now. The fact that we allow Borrow to accept a directory as an outpath is arbitrary; why do it for one of our tools and not others? Basically, we want to lower barrier of entry, so we want to allow anyone who might be using our CLI to simply supply a directory and not get an error message (or worse, an uncaught error). This has already happened to both myself and Bciar, so it would surely happen to others (less experienced than us). If that's the case, might as well centralize the logic, rather than implement this for each module that we currently have or may have in the future.

**Comment by jkpr** [comment]
First of all, the CLI should work with an output directory. However, the logic is contained in the CLI routine itself.

Your explanation for why this is the correct level of abstraction is lacking. I stated that `Workbook` / `Worksheet` is analogous to `xlsxwriter`'s Workbook and Worksheet class. You agreed that for `xlsxwriter`, it is doing the right thing only accepting a full path. Your reason for not applying the same reasoning to `pmix` is because it would require another wrapper. Unfortunately, that same wrapper-ing has to happen around `xlsxwriter`, so the logic (adding another wrapper layer) doesn't hold.

As for the magic value, remember this from [Zen of Python](https://www.python.org/dev/peps/pep-0020/):

> Explicit is better than implicit

Any call to `write_out` with a directory does not explicitly state where to save the file.

You wrote:

> Basically, we want to lower barrier of entry, so we want to allow anyone who might be using our CLI to simply supply a directory and not get an error message (or worse, an uncaught error).

This should already happen with the code as it is, do you have any counterexamples? We are currently speaking about the CLI.

The only reason borrow accepts a directory is because of this issue. However, it is a good idea since when the `-o` was omitted, it was following expected behavior creating a filename in the current directory or where the input files were.

You wrote:

> If that's the case, might as well centralize the logic, rather than implement this for each module that we currently have or may have in the future.

I disagree. Each tool / module, including numbering, workbook, borrow, is the piece of the code that is responsible for determining the output name of the file, not the `Workbook` class. `borrow` has `...-borrow.xlsx`, `numbering` has `...-numbering.xlsx`, workbook has `...rmws.xlsx`. This is perfectly logical.

Now how do we move forward?

Let's break out from the CLI the logic for determining an output file name. Each "client" module should know how to do that. That will make it easier for a non-CLI to take advantage. Furthermore, let's write some error messaging that is better.

Also, let's have a call about how your webapp uses this code, and we can make a plan from there.

**Comment by joeflack4** [comment]
@jkpr After stepping back for awhile and coming back, I think I can see the value in your perspective clearer.

I'm learning that one of the annoying things about software development is that principles can conflict, like a lot of other things in life, I guess. My zeal for being DRY conflicts a little with what you are saying. If we centralized more code into the wrapper class, it'd be less code overall between different tools (e.g. borrow). But I do think I see the value in what you are saying, regarding the correct level of abstraction for this.

As for the web app making use of these tools, thanks for offering to help plan. I don't think it will be necessary, though. The error came when Bciar was using the CLI and didn't realize he couldn't pass a directory. If he still has trouble, I'll just let him know that he has to pass the full path for now to each/some of these tools. And then in my own time I can add the logic to handle directory paths to the individual tools if necessary.
